library("shiny")
library("ggplot2")
library("tidyr")
library("reshape2")
library("stringr")
library("maps")
library("RColorBrewer")
library("rsconnect")
source("my_ui.R")
source("my_server.R")

shinyApp(ui = my_ui, server = my_server)